### ISSUE TITLE
i can't find kerala

### ISSUE THREAD

**Issue by outprog** [llSourcell/kerala#2]
i can't get github.com/siraj/go-kerala/kerala. how can i get it?

**Comment by eqr** [comment]
It seems current repository is Kerala. So use github.com/llSourcell/kerala instead. The problem is that it does hot work with current ipfs-go. I'm looking into fixing this but only in background so can not promise anything. This problem will hardly be addressed by somebody.

**Comment by yeanton** [comment]
hi! i have problem with install kerala and dapp sources, do you have new information about it. I was install ipfs-go 1.8. Maybe i could downgrade version of ipfs for stable work dapp?. thnx.
